targets:
  $default:
    builders:
      freezed:freezed:
        options:
          # Disable legacy (Dart 2 and older) utilites
          map: false
          when:
            when: false
            maybe_when: false
            when_or_null: false
        generate_for:
          - lib/**.dart
      json_serializable:json_serializable:
        options:
          # Serialize nested Freezed objects
          explicit_to_json: true
        generate_for:
          - lib/**.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/*.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**.dart
