name: blink_comparison
description: Simplifies comparing photos of tamper-evident seals and patterns using your eyes.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+5

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  auto_route: ^9.2.1+1
  bloc: ^8.0.2
  camera: ^0.11.0+1
  cross_file: ^0.3.1+5
  cupertino_icons: ^1.0.2
  devicelocale: ^0.8.1
  device_info_plus: ^10.1.1
  equatable: ^2.0.3
  extended_image: ^8.2.1
  ffi: ^2.1.3
  file: ^7.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.2
  flutter_email_sender: ^6.0.3
  flutter_image_compress: ^2.3.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.1+2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  injectable: ^2.4.4
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.0.0
  just_audio: ^0.9.16
  logger: ^2.4.0
  material_design_icons_flutter: ^7.0.7296
  open_settings_plus: ^0.3.3
  package_info_plus: ^8.0.1
  path_provider: ^2.1.3
  path_provider_android: ^2.0.12
  path_provider_ios: ^2.0.8
  path: ^1.8.0
  quiver: ^3.0.1
  responsive_builder: ^0.7.1
  sembast_sqflite: ^2.0.0+1
  sembast: ^3.1.0+2
  shared_preferences_android: ^2.0.11
  shared_preferences_ios: ^2.1.0
  shared_preferences: ^2.3.2
  showcaseview: ^3.0.0
  sodium: ^3.1.0
  sodium_libs: ^3.0.0
  sqflite_common_ffi: ^2.0.0+3
  sqflite: ^2.0.0+4
  swipe:
    git:
      url: https://github.com/proninyaroslav/swipe.git
      ref: patch-1
  url_launcher: ^6.0.9
  uuid: ^4.4.2
  wakelock_plus: ^1.2.7
  get_it: ^7.7.0
  async: ^2.11.0
  convert: ^3.1.1
  typed_data: ^1.3.2
  collection: ^1.18.0

dev_dependencies:
  analyzer: ^6.7.0
  auto_route_generator: ^9.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.4.11
  device_preview: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  intl_utils: ^2.6.0
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/audio/camera_shutter.mp3
    - assets/app_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
