name: Flutter Build CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.x"
      - name: Disable Google Analytics
        run: flutter config --no-analytics
      - name: Install dependencies
        run: flutter pub get
      - name: Build debug Android APK
        run: flutter build apk --debug
